version: "3.7"

services:

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/src:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules

  proxy:
    image: nginx:alpine
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/static
    depends_on:
      - frontend
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
  proxy_node_modules:
